### ISSUE TITLE
Folders/Tags to organize notes

### ISSUE THREAD

**Issue by WasteOfO2** [adil192/saber#428]
**Is your feature request related to a problem? Please describe.**

It can be difficult to organize notes when u have a lot of them, especially when u deal with multiple subjects in school for example, or juggling between multiple projects. Would also help with https://github.com/adil192/saber/issues/407

**Describe the solution you'd like**

Add the ability to add Tags or folders to easily categorize notes. Nested Folders preferred.

One can create, move or edit notes in a specific folder created by the user in Saber. Similar to how one interacts with files and folders on a PCs. 

Here is how One Note handles it.

![Screenshot_20230301-150953_OneNote](https://user-images.githubusercontent.com/45941793/222107546-0a3bdcb5-c27b-4996-a1bf-4e7c31002cf1.png)

Here is a more accurate depiction of what I want (how Notability handles it)

![image](https://user-images.githubusercontent.com/45941793/222120230-beb5bd38-cc41-4692-a7e0-4fd5f14d0a83.png)

Nested folders can be more robust than the Notebook-Section-Pages solution that One Note offers, and makes it easier to organise notes.

**Describe alternatives you've considered**

Add specific, user-defined tags to notes and the ability to search and filter notes based on tags queried. Like how music players do it with Genre, Artist, etc. Similarly with notes by adding tags like Physics, Chemistry, Short Notes, Questions, Thermodynamics, Drawings, etc.

Each note can have multiple tags.

**Device (please complete the following information):**
 - Device: Samsung Galaxy Tab S6 Lite LTE
 - OS: Lineage OS 19-20230121-NIGHTLY-gta4xl
 - Version: v0.9.5

Thank you for your wonderful work <3

***

## Tasks

- [X] Button to create a folder
- [x] Button to move a note to a different folder
- [X] Button to rename a note without opening it
- [x] Change the "new note" button in the Browse page to create a note in the current folder
- [ ] Buttons to rename and delete folders

**Comment by m0byn** [comment]
This would be very helpful!!

**Comment by Luciogi** [comment]
@adil192 add deletion of folder

**Comment by m0byn** [comment]
Should the folder structure be syncing? I have two tablets and on one I moved some notes to a folder, but on the other tablet nothing happened...

**Comment by WasteOfO2** [comment]
> Should the folder structure be syncing? I have two tablets and on one I moved some notes to a folder, but on the other tablet nothing happened...

Well in practice it should, but it would be better to open a new issue
